[project]
name = "cbr-to-sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastembed>=0.7.4",
    "flask>=3.1.2",
    "ipykernel>=7.1.0",
    "langchain>=1.0.7",
    "langchain-community>=0.4.1",
    "langchain-core>=1.0.5",
    "langchain-experimental>=0.4.0",
    "langchain-huggingface>=1.0.1",
    "langchain-ollama>=1.0.0",
    "langchain-openai>=1.0.3",
    "langchain-qdrant>=1.1.0",
    "mysql-connector-python>=9.5.0",
    "pymysql>=1.1.2",
    "python-dotenv>=1.2.1",
    "qdrant-client>=1.15.1",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.1.2",
    "sqlalchemy>=2.0.44",
    "sqlglot>=28.6.0",
    "umap-learn>=0.5.9.post2",
    "unstructured[pdf]>=0.18.20",
]
